'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=1)=>Number(n).toLocaleString(lang==='kk'?'kk-KZ':'ru-RU',{maximumFractionDigits:d});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), fc=features=>({type:'FeatureCollection',features});
const point=(coordinates,properties={})=>({type:'Feature',geometry:{type:'Point',coordinates},properties});
const colors={ink:'#1a2230',green:'#1d5fa8',late:'#965900',red:'#c0392b',line:'#e3ded3',paper:'#f5f3ee',lime:'#e8dcc2'};
let geo,country,snap,selected,map,mapReady=false,schema=false,following=false,playing=true,replaying=false,tempo=1;
let stream,retryTimer,retries=0,generation=0,receivedAt=0,lastFrame=0,lastForecast=0,forecastSeq=0,forecastController;
let history=[],forecasts=[],scheduleForecasts=[],correction={},drawn={},experiment=null,chatBusy=false,chatHistory=[],stationId='AST';
let incident='none',incidentAt=0,elapsed=0;
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const train=()=>snap?.state.trains.find(t=>t.train_id===selected);
const display=()=>snap?.display.find(t=>t.train_id===selected);
function error(message=''){$('error').textContent=message;$('error').hidden=!message;}
function clock(ts){return ts?.slice(11,19)||'—';}
function currentState(){const s=structuredClone(snap.state);if(experiment){const t=s.trains.find(t=>t.train_id===experiment.id);if(t){t.delay_s=experiment.delay*60;t.time_reserve_min=experiment.reserve;}}return s;}
function applySnapshot(data,record=true){if(record&&snap&&data.elapsed_s<snap.elapsed_s-.1&&!replaying)return;
  correction=Object.fromEntries(data.display.map(d=>[d.train_id,(drawn[d.train_id]??d.corridor_km)-d.corridor_km]));snap=data;elapsed=data.elapsed_s;receivedAt=performance.now();
  if(record){history.push(data);history=history.filter(s=>s.elapsed_s>=elapsed-900).slice(-901);$('replay').max=history.length-1;$('replay').value=history.length-1;}
  $('clock').textContent=clock(data.ts);$('connection').textContent=T(playing?'connected':'pause');renderInspector();renderDiagram();renderStation();updateInfrastructure();renderDashboard();if(data.sent_at){const sent=Date.parse(data.sent_at);requestAnimationFrame(()=>{paintTimes.push(Math.max(0,Date.now()-sent));paintTimes=paintTimes.slice(-200);const p=[...paintTimes].sort((a,b)=>a-b);$('connection').textContent=T(playing?'connected':'pause')+' · '+fmt(p[Math.floor((p.length-1)*.95)],0)+' '+T('ms');});}
  if(performance.now()-lastForecast>3000)calculate();
  if(analysisResult)renderAnalysis();
  else if(!analysisInitialized){analysisInitialized=true;queueMicrotask(runAnalysis);}
}
function connect(){clearTimeout(retryTimer);stream?.close();if(!playing||replaying)return;const token=++generation;
  const q=new URLSearchParams({elapsed:String(elapsed),speed:String(tempo),incident,incident_at:String(incidentAt)});stream=new EventSource('/demo/stream?'+q);
  stream.addEventListener('state',e=>{if(token!==generation)return;try{const data=JSON.parse(e.data);retries=0;applySnapshot(data);error();}catch{error(T('requestError'));}});
  stream.onerror=()=>{if(token!==generation)return;stream.close();$('connection').textContent=T('connecting');error(T('connectionError'));receivedAt=0;retryTimer=setTimeout(connect,Math.min(15000,1000*2**retries++));};
}
function pause(){playing=false;generation++;stream?.close();clearTimeout(retryTimer);$('play').textContent=T('resume');$('connection').textContent=T('pause');correction={};}
function resume(){experiment=null;if(replaying)history=history.filter(s=>s.elapsed_s<=elapsed);replaying=false;playing=true;$('play').textContent=T('pause');$('replay-label').textContent=T('live');connect();}
function coordsAt(km){const f=geo.features.find(f=>km>=f.properties.start_km-1e-7&&km<=f.properties.end_km+1e-7)||geo.features.at(-1),p=f.properties;
  const fraction=clamp((km-p.start_km)/p.length_km,0,1),line=f.geometry.coordinates;
  // Arc-length interpolation supports future multi-vertex block geometry.
  const lengths=line.slice(1).map((b,i)=>{const a=line[i],rad=Math.PI/180;return Math.hypot((b[0]-a[0])*Math.cos((a[1]+b[1])*rad/2),b[1]-a[1]);});
  let distance=fraction*lengths.reduce((a,b)=>a+b,0);for(let i=0;i<lengths.length;i++){if(distance<=lengths[i]||i===lengths.length-1){const q=lengths[i]?distance/lengths[i]:0;return line[i].map((a,j)=>a+(line[i+1][j]-a)*q);}distance-=lengths[i];}return line[0];
}
function visualKm(d,now){const t=snap.state.trains.find(t=>t.train_id===d.train_id);const age=receivedAt?(now-receivedAt)/1000:0;
  const dt=playing&&!replaying&&!reduced?Math.min(1.3,age)*tempo:0;const p=geo.features.find(f=>f.properties.id===t.position.block_id).properties;
  const target=clamp(d.corridor_km+d.direction*t.speed*dt/3600,p.start_km,p.end_km);
  return clamp(target+(correction[d.train_id]||0)*Math.max(0,1-age/.25),0,geo.length_km);
}
function fallbackProjection([lon,lat]){const w=$('map-shell').clientWidth,h=$('map-shell').clientHeight;const extent=following&&display()?(()=>{const [x,y]=coordsAt(display().corridor_km);return[x-1,y-1,x+1,y+1];})():[67.9,42.7,78.2,54];
  const scale=Math.min((w-90)/((extent[2]-extent[0])*.67),(h-70)/(extent[3]-extent[1]));return {x:w/2+(lon-(extent[0]+extent[2])/2)*.67*scale,y:h/2-(lat-(extent[1]+extent[3])/2)*scale};}
const project=coord=>mapReady&&!schema?map.project(coord):fallbackProjection(coord);
function fit(){following=false;$('follow').setAttribute('aria-pressed','false');if(mapReady)map.fitBounds([[68.8,43.05],[77.5,53.55]],{padding:{top:35,bottom:45,left:50,right:90},duration:reduced?0:450});}
function focusTrain(){if(!display())return;if(mapReady&&!schema)map.easeTo({center:coordsAt(display().corridor_km),zoom:Math.max(7,map.getZoom()),duration:reduced?0:350});}
function updateInfrastructure(){if(!mapReady||!snap)return;const features=geo.features.map(f=>{const b=snap.state.infra.blocks.find(b=>b.id===f.properties.id);return {...f,properties:{...f.properties,closed:b.closed,occupied:b.occupied,limited:b.speed_limit<geo.features.find(x=>x.properties.id===b.id).properties.speed_limit}};});map.getSource('infra').setData(fc(features));}
function initializeMap(){try{if(!window.maplibregl)throw Error('MapLibre unavailable');map=new maplibregl.Map({container:'map',style:{version:8,sources:{},layers:[{id:'paper',type:'background',paint:{'background-color':colors.paper}}]},center:[72,49],zoom:4,attributionControl:true});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');new ResizeObserver(()=>{map.resize();}).observe($('map-shell'));
  map.on('load',()=>{map.addSource('country',{type:'geojson',data:country});map.addLayer({id:'country-fill',type:'fill',source:'country',paint:{'fill-color':css('--surface2')}});map.addLayer({id:'country-edge',type:'line',source:'country',paint:{'line-color':css('--border'),'line-width':1.5}});
    map.addSource('infra',{type:'geojson',data:geo});map.addLayer({id:'rail-halo',type:'line',source:'infra',paint:{'line-color':css('--surface'),'line-width':6}});map.addLayer({id:'rail',type:'line',source:'infra',paint:{'line-color':colors.ink,'line-width':2}});
    map.addLayer({id:'occupied',type:'line',source:'infra',filter:['==',['get','occupied'],true],paint:{'line-color':colors.green,'line-width':4}});
    map.addLayer({id:'closed',type:'line',source:'infra',filter:['==',['get','closed'],true],paint:{'line-color':colors.red,'line-width':7,'line-dasharray':[1,1]}});
    map.addSource('trains',{type:'geojson',data:fc([])});map.addLayer({id:'train-points',type:'circle',source:'trains',paint:{'circle-radius':['case',['get','selected'],7,4],'circle-color':['get','color'],'circle-stroke-width':2,'circle-stroke-color':colors.paper}});
    mapReady=true;document.querySelector('.maplibregl-ctrl-zoom-in')?.setAttribute('aria-label',T('zoomIn'));document.querySelector('.maplibregl-ctrl-zoom-out')?.setAttribute('aria-label',T('zoomOut'));fit();updateInfrastructure();$('map-caption').textContent=T('mapCaption');
  });map.on('error',()=>{if($('basemap').checked){$('basemap').checked=false;if(map.getLayer('osm-layer'))map.setLayoutProperty('osm-layer','visibility','none');$('map-caption').textContent='Подложка недоступна · локальный маршрут работает';}});
  map.getCanvas().addEventListener('webglcontextlost',e=>{e.preventDefault();setSchema(true);error(T('noWebgl'));});
  }catch{setSchema(true);$('map-caption').textContent=T('noWebgl');}}
function setSchema(value){schema=value;$('map').hidden=value;$('schema-mode').setAttribute('aria-pressed',String(value));$('map-mode').setAttribute('aria-pressed',String(!value));$('basemap').disabled=value;map?.resize();$('map-caption').textContent=T('mapCaption');}
let forecastStatus='pending', previewChoice=null;
let lang=localStorage.getItem('turkisib-language')||'ru',advisories=[],page='overview',drawerKind='train',decision=null,ack=false,tourStep=0;
let zoomWindow=null,dragStart=null,decisionTimer=null,decisionStart=0,evidenceLoaded=false,qualityDrawn=0,metricsDurations=[],frameDurations=[],lastPaint=0,drawerOpener=null,qualityTarget=null,qualityAnimation=0,paintTimes=[];
const css=name=>getComputedStyle(document.documentElement).getPropertyValue(name).trim();
const T=(key,vars={})=>i18next.t(key,vars);
const shortId=id=>id?.split('-').at(-1)||'—';
const kind=t=>t?.type==='груз'?'freight':t?.type==='скоростной'?'highspeed':'passenger';
const typeColor=t=>css('--'+(kind(t)==='highspeed'?'primary':kind(t)));
const stationName=id=>geo?.stations.find(s=>s.id===id)?.name||id;
const minute=n=>`${fmt(n,0)} ${T('min')}`;
const icon=path=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`;
const navItems=[['overview','M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z'],['diagram','M3 3v18h18M6 17l5-8 4 5 6-9'],['scenarios','M12 3 2 21h20ZM12 9v5M12 17v1'],['comparison','M4 20V9h5v11M15 20V3h5v17'],['whatif','M5 3v7c0 6 14 0 14 8v3M5 10v11M16 18l3 3 3-3'],['analytics','M3 20h18M6 16V9M12 16V4M18 16v-5'],['lab','M9 3h6M10 3v7L4 20h16l-6-10V3M7 15h10'],['settings','M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6'],['readiness','m4 12 5 5L20 6']];
function localize(){document.documentElement.lang=lang;document.querySelector('.maplibregl-ctrl-zoom-in')?.setAttribute('aria-label',T('zoomIn'));document.querySelector('.maplibregl-ctrl-zoom-out')?.setAttribute('aria-label',T('zoomOut'));document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=T(e.dataset.i18n));$('language').value=lang;$('question').placeholder=T('explainQuestion');$('theme').textContent=T(document.documentElement.dataset.theme==='dark'?'light':'dark');$('play').textContent=T(playing?'pause':'resume');$('connection').textContent=T(playing?'connected':'pause');document.querySelector('.rail').innerHTML=navItems.map(([key,path])=>`<button data-page="${key}" aria-current="${page===key?'page':'false'}">${icon(path)}<span>${T(key==='whatif'?'experiment':key)}</span></button>`).join('');$('page-title').textContent=T(page==='whatif'?'experiment':page);for(const [id,key] of [['tempo','tempo'],['role','dispatcher'],['map-overlay','map'],['diagram','diagram'],['station-picker','station'],['drawer','train'],['axis','axisKm'],['horizon','step30']])$(id)?.setAttribute('aria-label',T(key));document.querySelector('.rail').setAttribute('aria-label',T('overview'));if(snap){$('train-picker').innerHTML=snap.state.trains.map(t=>`<option value="${t.train_id}">${shortId(t.train_id)} · ${T(kind(t))} · ${stationName(snap.display.find(d=>d.train_id===t.train_id).origin)}</option>`).join('');$('chat-provider').textContent=T('llmFallback');renderDashboard();renderInspector();renderDiagram();renderStation();renderComparison();renderDecisionText();if(!$('tour').hidden)showTour();}if(evidenceLoaded)loadEvidence();}
function setTheme(value){document.documentElement.dataset.theme=value;localStorage.setItem('turkisib-theme',value);for(const [key,token] of Object.entries({ink:'--text',green:'--primary',late:'--warning',red:'--critical',line:'--border',paper:'--bg',lime:'--sand'}))colors[key]=css(token);if(mapReady){map.setPaintProperty('paper','background-color',colors.paper);map.setPaintProperty('country-fill','fill-color',css('--surface2'));map.setPaintProperty('country-edge','line-color',colors.line);map.setPaintProperty('rail','line-color',colors.ink);map.setPaintProperty('rail-halo','line-color',css('--surface'));}if(window.i18next?.isInitialized)$('theme').textContent=T(value==='dark'?'light':'dark');if(evidenceLoaded)loadEvidence();}
function navigate(key){page=key;const overview=key==='overview'||key==='diagram';$('overview-grid').hidden=!overview;document.querySelectorAll('.secondary').forEach(e=>e.hidden=true);const panel=$(key+'-panel');if(panel)panel.hidden=false;if(key==='readiness')$('readiness').hidden=false;if(key==='whatif'){$('comparison-panel').hidden=false;openDrawer('train');$('experiment').open=true;}$('page-title').textContent=T(key==='whatif'?'experiment':key);document.querySelectorAll('[data-page]').forEach(e=>e.setAttribute('aria-current',String(e.dataset.page===key?'page':'false')));if(key==='lab')loadEvidence();if(overview)requestAnimationFrame(()=>{map?.resize();renderDiagram();if(key==='diagram')$('diagram-panel').scrollIntoView({behavior:reduced?'auto':'smooth'});});}
function openDrawer(which='train'){drawerOpener=document.activeElement;drawerKind=which;$('drawer').hidden=false;$('train-detail').hidden=which!=='train';$('station-detail').hidden=which!=='station';if(which==='station'){$('selected-title').textContent=stationName(stationId);renderStation();}else renderInspector();$('drawer-close').focus({preventScroll:true});}
function closeDrawer(){$('drawer').hidden=true;drawerOpener?.focus?.({preventScroll:true});}
function select(id){if(!snap?.state.trains.some(t=>t.train_id===id))return;selected=id;stationId=display().next_station;$('station-picker').value=stationId;experiment=null;renderInspector();renderDiagram();renderStation();renderDashboard();renderAnalysis();calculate();if(following)focusTrain();}
async function api(path,body,signal){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal});if(!r.ok)throw Error(T('requestError')+' ('+r.status+')');return r.json();}
async function calculate(){if(!snap)return;lastForecast=performance.now();const seq=++forecastSeq;forecastController?.abort();forecastController=new AbortController();try{const start=performance.now();const advice=await api('/forecast/advisory',currentState(),forecastController.signal);if(seq!==forecastSeq)return;advisories=advice;forecastStatus='success';metricsDurations.push(performance.now()-start);metricsDurations=metricsDurations.slice(-100);renderForecast();}catch(e){if(e.name!=='AbortError'){forecastStatus='error';advisories=[];forecasts=[];renderForecast();}}}
function renderInspector(){const t=train(),d=display();if(!t)return;if(drawerKind==='train')$('selected-title').textContent=shortId(selected)+' · '+T(kind(t));$('train-picker').value=selected;$('train-kind').textContent=T(kind(t));$('next-station').textContent=stationName(d.next_station);$('train-speed').textContent=fmt(t.speed,0)+' '+T('kmh');$('distance').textContent=fmt(d.distance_to_station_km,1)+' '+T('km');$('actual-delay').textContent=minute(t.delay_s/60);$('actual-delay').className=t.delay_s>=600?'critical-text':t.delay_s>=180?'warning-text':'';$('eta').textContent=d.eta_s===null?T('stopped'):`${Math.floor(d.eta_s/60)}:${String(Math.floor(d.eta_s%60)).padStart(2,'0')}`;$('planned-eta').textContent=clock(d.scheduled_arrival);if(!experiment){$('delay').value=t.delay_s/60;$('reserve').value=t.time_reserve_min;}$('delay-output').textContent=minute(experiment?.delay??t.delay_s/60);$('reserve-output').textContent=minute(experiment?.reserve??t.time_reserve_min);$('selected-key').textContent=shortId(selected);$('technical').textContent=JSON.stringify({ood_features:advisories.find(a=>a.train_id===selected)?.ood_features,train_id:selected,block_id:t.position.block_id,category:t.type,priority:t.priority,source:'SIMULATED',direction:d.direction,domain:t.source_domain},null,2);renderForecast();}
function renderForecast(){const a=advisories.find(f=>f.train_id===selected);if(!a){$('prediction').textContent=T(forecastStatus==='error'?'forecastUnavailable':'loading');$('forecast-retry').hidden=forecastStatus!=='error';for(const id of ['decomposition','risk','prediction-note','profile-note','kz-schedule','model-badge'])$(id).replaceChildren();return;}$('forecast-retry').hidden=true;$('prediction').textContent=a.reliable?`≈${minute(a.delay_interval_min[1])} (${fmt(a.delay_interval_min[0],0)}–${fmt(a.delay_interval_min[2],0)})`:T('unreliable');$('prediction').className='prediction '+(!a.reliable?'warning-text':'');$('model-badge').textContent=T('pkpTransfer');$('prediction-note').textContent=a.ood_features?.length?T('ood'):T('noRisk');$('decomposition').innerHTML=[['delay',a.current_delay_min],['knownWait',a.known_wait_min],['restrictionExtra',a.restriction_extra_min],['mlAddition',a.ml_delta_min]].map(([key,v])=>`<div><span>${T(key)}</span><strong>${v===null||v===undefined?T('noRisk'):minute(v)}</strong></div>`).join('');$('risk').textContent=T('riskGrowth')+': '+(a.reliable?fmt(a.delay_growth_probability*100,1)+'%':T('noRisk'));$('profile-note').textContent=T('intervalNote');$('kz-schedule').textContent=T('formula');}
function animateQuality(value){if(qualityTarget===value)return;qualityTarget=value;cancelAnimationFrame(qualityAnimation);const from=qualityDrawn,start=performance.now();function tick(now){const progress=reduced?1:Math.min(1,(now-start)/360);qualityDrawn=from+(value-from)*(1-Math.pow(1-progress,3));$('quality-value').textContent=fmt(qualityDrawn,0);$('quality-ring').setAttribute('stroke-dasharray',`${qualityDrawn/100*321} 321`);if(progress<1)qualityAnimation=requestAnimationFrame(tick);}qualityAnimation=requestAnimationFrame(tick);}
function renderDashboard(){if(!snap)return;const q=snap.quality;if(q){animateQuality(q.score);$('quality-ring').style.stroke=css(q.category==='critical'?'--critical':q.category==='attention'?'--warning':'--ok');$('quality-state').textContent=T(q.category);$('quality-state').className=q.category==='critical'?'critical-text':q.category==='attention'?'warning-text':'';const top=[...q.factors].sort((a,b)=>b.points-a.points);$('quality-reason').textContent=top[0].points?T('factor_'+top[0].key):T('noAlerts');$('factors').innerHTML=top.map(f=>`<div class="factor"><span>${T('factor_'+f.key)}</span><span class="mono">−${fmt(f.points,1)}</span><div class="factor-track"><div class="factor-bar" style="transform:scaleX(${f.points/30})"></div></div></div>`).join('')+`<p class="caption">${T('formulaNote')}</p>`;const past=history.filter(s=>s.elapsed_s>=elapsed-300&&s.quality);const first=past[0]?.quality.score;const delta=first===undefined?0:q.score-first;$('quality-trend').textContent=(delta>=0?'+':'')+fmt(delta,1)+' / 5 '+T('min');$('quality-spark').innerHTML=`<polyline points="${past.map((s,i)=>`${i/Math.max(1,past.length-1)*160},${28-s.quality.score*.25}`).join(' ')}" fill="none" stroke="${css('--primary')}" stroke-width="2"/>`;}
 const active=snap.incident_active;$('alerts-count').textContent=active?'1':'0';$('alerts').innerHTML=active?`<article class="telegram"><time>${clock(snap.ts)}</time><strong class="${incident==='restriction'?'warning-text':'critical-text'}">${T(incident==='chaos'?'chaos':incident)}</strong><p>${T('incidentUntil',{time:new Date(Date.parse(snap.ts)+(snap.incident_end_s-elapsed)*1000).toLocaleTimeString(lang==='kk'?'kk-KZ':'ru-RU',{timeZone:'Asia/Almaty',hour:'2-digit',minute:'2-digit',hour12:false})})}</p>${ack?`<span class="caption">${T('acknowledged')}</span>`:''}</article>`:`<article class="telegram"><strong>${T('noAlerts')}</strong><p class="caption">${T('synthetic')}</p></article>`;
 const focused=document.activeElement?.closest('#train-list [data-train]')?.dataset.train;
 $('train-list').innerHTML=snap.state.trains.map(t=>{const d=snap.display.find(d=>d.train_id===t.train_id),status=t.delay_s>=600?'critical':t.delay_s>=180?'attention':'normal';return `<tr aria-selected="${t.train_id===selected}"><td><button data-train="${t.train_id}"><span><i class="train-type" style="background:${typeColor(t)}"></i>${shortId(t.train_id)}</span><small>${T(kind(t))}</small></button></td><td><small>${stationName(d.origin)}<br>→ ${stationName(d.destination)}</small></td><td><span class="status ${status}">${status==='normal'?'✓':status==='attention'?'!':'!'} ${minute(t.delay_s/60)}</span></td></tr>`;}).join('');if(focused)$('train-list').querySelector(`[data-train="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});
 const sorted=[...metricsDurations].sort((a,b)=>a-b);$('performance').textContent=sorted.length?`HTTP p95 ${fmt(sorted[Math.floor((sorted.length-1)*.95)],0)} ${T('ms')}`:'';
 $('analytics-content').textContent=T('totalDelay')+': '+fmt(snap.state.trains.reduce((a,t)=>a+t.delay_s/60,0),1)+' · '+T('compute')+': '+(sorted.length?fmt(sorted[Math.floor(sorted.length/2)],1):'—');}
function renderMap(now){if(!snap||!geo||$('overview-grid').hidden)return;const w=$('map-shell').clientWidth,h=$('map-shell').clientHeight;if(!w)return;$('map-overlay').setAttribute('viewBox',`0 0 ${w} ${h}`);let html='';const path=cs=>cs.map((c,i)=>{const p=project(c);return`${i?'L':'M'}${p.x},${p.y}`;}).join(' ');
 if(schema||!mapReady){for(const f of country.features){const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];for(const poly of polys)html+=`<path d="${path(poly[0])}Z" fill="${css('--surface2')}" stroke="${colors.line}"/>`;}for(const f of geo.features){const b=snap.state.infra.blocks.find(b=>b.id===f.properties.id),closed=b.closed&&$('layer-restrictions').checked;html+=`<path d="${path(f.geometry.coordinates)}" fill="none" stroke="${css('--surface')}" stroke-width="6"/><path d="${path(f.geometry.coordinates)}" fill="none" stroke="${closed?colors.red:colors.ink}" stroke-width="${closed?5:2}" ${closed?'stroke-dasharray="3 3"':''}/>`;}}
 const d=display();if($('layer-forecast').checked&&d){const trail=history.filter(s=>s.elapsed_s<=elapsed&&s.elapsed_s>=elapsed-600).map(s=>s.display.find(x=>x.train_id===selected)).filter(Boolean).map(d=>coordsAt(d.corridor_km));if(trail.length>1)html+=`<path d="${path(trail)}" stroke="${colors.green}" stroke-width="3" fill="none"/>`;const t=train();const end=clamp(d.corridor_km+d.direction*t.speed/4,Math.min(...[d.origin,d.destination].map(id=>geo.stations.find(s=>s.id===id).km)),Math.max(...[d.origin,d.destination].map(id=>geo.stations.find(s=>s.id===id).km)));html+=`<path d="${path(Array.from({length:20},(_,i)=>coordsAt(d.corridor_km+(end-d.corridor_km)*i/19)))}" stroke="${colors.green}" stroke-dasharray="5 5" fill="none"/>`;const g=project(coordsAt(d.scheduled_km));html+=`<circle cx="${g.x}" cy="${g.y}" r="9" fill="none" stroke="${colors.ink}" stroke-dasharray="3 3"/>`;}
 const markers=snap.display.map(d=>{const p=project(coordsAt(visualKm(d,now)));return {x:p.x+d.direction*8-18,y:p.y-18,w:36,h:36};});
 const labels=[];const intersects=(a,b)=>a.x<b.x+b.w+5&&a.x+a.w+5>b.x&&a.y<b.y+b.h+5&&a.y+a.h+5>b.y;
 for(const [i,s] of geo.stations.entries()){const p=project(s.coordinates),v=snap.stations.find(v=>v.id===s.id);if(p.x<0||p.x>w||p.y<0||p.y>h)continue;
 const candidates=[];for(let cy=14;cy<h-65;cy+=34)for(const cx of [8,w-154,clamp(p.x-178,8,w-154),clamp(p.x+34,8,w-154)])candidates.push({x:cx,y:cy-12,w:146,h:30});
 candidates.sort((a,b)=>Math.hypot(a.x+73-p.x,a.y+15-p.y)-Math.hypot(b.x+73-p.x,b.y+15-p.y));const box=candidates.find(c=>![...labels,...markers].some(b=>intersects(c,b)))||candidates.find(c=>!labels.some(b=>intersects(c,b)))||candidates[0];labels.push(box);const x=box.x,y=box.y+12,left=x<p.x;
 html+=`<g data-station="${s.id}" role="button" tabindex="0" aria-label="${T('station')} ${esc(s.name)}"><path d="M${p.x} ${p.y}L${x+(left?144:0)} ${y}" stroke="${colors.line}" fill="none"/><circle cx="${p.x}" cy="${p.y}" r="20" fill="transparent"/><circle cx="${p.x}" cy="${p.y}" r="8" fill="${colors.paper}" stroke="${colors.line}" stroke-width="3"/>${$('layer-occupancy').checked?`<circle cx="${p.x}" cy="${p.y}" r="8" fill="none" stroke="${v.problem?colors.red:colors.green}" stroke-width="3" stroke-dasharray="${v.occupied/v.capacity*50.26} 51" class="${v.problem&&!ack?'problem-ring':''}"/>`:''}<text class="station-name" x="${x}" y="${y}">${esc(s.name)}</text><text x="${x}" y="${y+15}">${T('freeTracks',{n:v.capacity-v.occupied,m:v.capacity})}</text></g>`;}
 const points=[];if($('layer-trains').checked)for(const d of [...snap.display].sort((a,b)=>(a.train_id===selected)-(b.train_id===selected))){const t=snap.state.trains.find(t=>t.train_id===d.train_id),km=visualKm(d,now);drawn[d.train_id]=km;const c=coordsAt(km),p=project(c),next=project(coordsAt(clamp(km+d.direction*.2,0,geo.length_km)));const angle=Math.atan2(next.y-p.y,next.x-p.x)*180/Math.PI;p.x+=d.direction*8;const col=typeColor(t),chosen=d.train_id===selected;points.push(point(c,{selected:chosen,color:col}));const shape=kind(t)==='freight'?'<path d="M-8-5H7V5H-8Z M7-5 12 0 7 5"/>':kind(t)==='highspeed'?'<path d="M-10-5 12 0-10 5Z"/>':'<path d="M-10-4H5L11 0 5 4H-10Z"/>';html+=`<g data-train="${d.train_id}" role="button" tabindex="${chosen?0:-1}" aria-label="${shortId(d.train_id)} · ${T(kind(t))}"><circle cx="${p.x}" cy="${p.y}" r="20" fill="transparent"/><circle cx="${p.x}" cy="${p.y}" r="12" fill="none" stroke="${t.delay_s>=600?colors.red:t.delay_s>=180?colors.late:css('--ok')}" stroke-width="1.5"/><g transform="translate(${p.x},${p.y}) rotate(${angle})" fill="${col}" stroke="${chosen?colors.ink:css('--surface')}" stroke-width="${chosen?2:1}">${shape}</g>${chosen?`<text x="${clamp(p.x+24,10,w-70)}" y="${clamp(p.y+27,20,h-28)}">${shortId(d.train_id)}</text>`:''}</g>`;}
 if(mapReady&&!schema)map.getSource('trains').setData(fc(points));const focus=document.activeElement?.closest('#map-overlay [data-train],#map-overlay [data-station]'),key=focus?.dataset.train||focus?.dataset.station;$('map-overlay').innerHTML=html;if(key)$('map-overlay').querySelector(`[data-train="${CSS.escape(key)}"],[data-station="${CSS.escape(key)}"]`)?.focus({preventScroll:true});if(following&&mapReady&&!schema&&d)map.setCenter(coordsAt(drawn[selected]??d.corridor_km));}
function plannedKm(tid,seconds){const timetable=geo.timetable.filter(s=>s.train_id===tid),points=[];for(const stop of timetable)for(const key of ['scheduled_arrival','scheduled_departure'])if(stop[key])points.push([Date.parse(stop[key]),geo.stations.find(s=>s.id===stop.station_id).km]);points.sort((a,b)=>a[0]-b[0]);const ms=Date.parse(snap.ts)+seconds*1000;if(ms<=points[0][0])return points[0][1];for(let i=1;i<points.length;i++)if(ms<=points[i][0]){const [a,x]=points[i-1],[b,y]=points[i];return x+(y-x)*(ms-a)/(b-a||1);}return points.at(-1)[1];}
function diagramScale(){const step=Number($('horizon').value),window=zoomWindow||[-step,step*2],x=m=>185+(m-window[0])/(window[1]-window[0])*670;const y=km=>{if($('axis').value==='km')return 18+km/geo.length_km*210;let i=geo.stations.findIndex((s,j)=>j<8&&km>=s.km&&km<=geo.stations[j+1].km);if(i<0)i=7;return 18+(i+(km-geo.stations[i].km)/(geo.stations[i+1].km-geo.stations[i].km))*26.25;};return {window,x,y,step};}
function renderDiagram(){if(!snap)return;const {window:[lo,hi],x,y,step}=diagramScale();let svg='<defs><pattern id="closure-hatch" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8 8 0" stroke="'+colors.red+'" opacity=".35"/></pattern><clipPath id="plot"><rect x="185" y="10" width="670" height="222"/></clipPath></defs>';let lastLabel=-50;for(const s of geo.stations){const py=y(s.km),labelY=Math.max(py,lastLabel+18);lastLabel=labelY;svg+=`<line x1="185" x2="855" y1="${py}" y2="${py}" stroke="${colors.line}"/><path d="M165 ${labelY} 180 ${py}" stroke="${colors.line}" fill="none"/><text x="160" y="${labelY+4}" text-anchor="end">${esc(s.name)}</text>`;}
 const ticks=[];for(let m=Math.ceil(lo/step)*step;m<=hi;m+=step)ticks.push(m);if(!ticks.includes(0)&&lo<=0&&hi>=0)ticks.push(0);for(const m of ticks){const label=new Date(Date.parse(snap.ts)+m*60000).toLocaleTimeString(lang==='kk'?'kk-KZ':'ru-RU',{timeZone:'Asia/Almaty',hour:'2-digit',minute:'2-digit',hour12:false});svg+=`<line x1="${x(m)}" x2="${x(m)}" y1="10" y2="235" stroke="${m===0?colors.ink:colors.line}"/><text x="${x(m)}" y="260" text-anchor="middle">${m===0?T('now'):label}</text>`;}
 svg+='<g clip-path="url(#plot)">';if(snap.incident_active&&['closure','chaos'].includes(incident))svg+=`<rect x="${x(Math.max(lo,0))}" y="${y(65)}" width="${Math.max(0,x(Math.min(hi,(snap.incident_end_s-elapsed)/60))-x(Math.max(lo,0)))}" height="${y(174)-y(65)}" fill="url(#closure-hatch)"/>`;
 for(const d of snap.display){const t=snap.state.trains.find(t=>t.train_id===d.train_id),chosen=d.train_id===selected,col=typeColor(t),past=history.filter(s=>s.elapsed_s<=elapsed&&s.elapsed_s>=elapsed+lo*60).map(s=>({m:(s.elapsed_s-elapsed)/60,d:s.display.find(v=>v.train_id===d.train_id)})).filter(v=>v.d);const plan=Array.from({length:50},(_,i)=>{const m=lo+(hi-lo)*i/49;return `${x(m)},${y(plannedKm(d.train_id,m*60))}`;}).join(' ');const routeEnds=[d.origin,d.destination].map(id=>geo.stations.find(s=>s.id===id).km),end=clamp(d.corridor_km+d.direction*t.speed*hi/60,Math.min(...routeEnds),Math.max(...routeEnds));svg+=`<g data-train="${d.train_id}" role="button" tabindex="0" opacity="${chosen?1:.3}"><polyline points="${plan}" stroke="${col}" fill="none" stroke-width="1"/><polyline points="${past.map(p=>`${x(p.m)},${y(p.d.corridor_km)}`).join(' ')}" stroke="${col}" fill="none" stroke-width="${chosen?3:2}"/><line x1="${x(0)}" y1="${y(d.corridor_km)}" x2="${x(hi)}" y2="${y(end)}" stroke="${col}" stroke-width="${chosen?3:1.5}" stroke-dasharray="6 4"/><line x1="${x(0)}" y1="${y(d.corridor_km)}" x2="${x(hi)}" y2="${y(end)}" stroke="transparent" stroke-width="12"/><circle cx="${x(0)}" cy="${y(d.corridor_km)}" r="${chosen?5:2}" fill="${col}"/><title>${shortId(d.train_id)} · ${T(kind(t))}</title></g>`;}
 svg+='</g>';const focused=document.activeElement?.closest('#diagram [data-train]')?.dataset.train;$('diagram').innerHTML=svg;if(focused)$('diagram').querySelector(`[data-train="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});}
function renderStation(){if(!snap)return;const s=geo.stations.find(s=>s.id===stationId),v=snap.stations.find(v=>v.id===stationId);let svg='';for(let i=0;i<s.tracks;i++){const yy=35+i*38;svg+=`<path d="M15 100 65 ${yy}H335L385 100" fill="none" stroke="${colors.line}" stroke-width="2"/><text x="70" y="${yy-10}">${T('track',{n:i+1})}</text>`;if(v.trains[i])svg+=`<g data-train="${v.trains[i]}" role="button" tabindex="0"><rect x="120" y="${yy-6}" width="150" height="12" rx="3" fill="${colors.green}"/><text x="280" y="${yy+5}">${shortId(v.trains[i])}</text></g>`;}svg+=`<text x="16" y="200">${T('freeTracks',{n:v.capacity-v.occupied,m:v.capacity})}</text>`;const focused=document.activeElement?.closest('#station [data-train]')?.dataset.train;$('station').innerHTML=svg;if(focused)$('station').querySelector(`[data-train="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});const arrivals=geo.timetable.filter(a=>a.station_id===stationId&&a.scheduled_arrival&&Date.parse(a.scheduled_arrival)>=Date.parse(snap.ts)&&Date.parse(a.scheduled_arrival)<=Date.parse(snap.ts)+3600000);$('station-facts').innerHTML=Array.from({length:s.tracks},(_,i)=>`<div>${T('track',{n:i+1})}: ${v.trains[i]?T('occupied')+' · '+shortId(v.trains[i]):T('free')}</div>`).join('')+`<p>${T('stationNote')}</p><p>${T('futureOccupancy')}</p><h3>${T('arrivals')}</h3>`+arrivals.map(a=>`<div>${shortId(a.train_id)} · ${clock(a.scheduled_arrival)}</div>`).join('');}
function frame(now){requestAnimationFrame(frame);if(document.hidden||now-lastFrame<(!playing||reduced?250:tempo===10?32:16))return;const start=performance.now();renderMap(now);frameDurations.push(performance.now()-start);frameDurations=frameDurations.slice(-240);lastFrame=now;}
function buildDecision(){const seed=Number($('seed').value)||42;const pool=snap.display.filter(d=>d.origin==='KOK'||d.destination==='KOK');const pair=[pool.find(d=>d.direction===1),pool.find(d=>d.direction===-1)].filter(Boolean);if(pair.length<2)return;const start=performance.now(),jobs=pair.map((d,i)=>({id:d.train_id,release:Math.round((seed*(i+3)%13)+snap.state.trains.find(t=>t.train_id===d.train_id).delay_s/60),duration:8+(seed+i*7)%9}));const opening=Math.max(0,(snap.incident_end_s-elapsed)/60);function run(order,hold=false){let time=opening+(hold?5:0);let total=0,energy=0;const slots=[];for(const index of order){const j=jobs[index],begin=Math.max(time,j.release),duration=j.duration*(hold?2:1);total+=begin-j.release;energy+=duration*(hold?.5:1)**2;slots.push({id:j.id,start:begin,end:begin+duration});time=begin+duration+2;}return {delay:total,conflicts:0,energy,slots,score:Math.max(0,100-total/2),ms:0};}const alternatives={A:run([0,1]),B:run([1,0]),C:run([0,1],true)};const fifo=run(jobs[0].release<=jobs[1].release?[0,1]:[1,0]);const ms=performance.now()-start;Object.values(alternatives).forEach(a=>a.ms=ms);fifo.ms=ms;previewChoice=null;decision={seed,ts:snap.ts,elapsed:snap.elapsed_s,incident:snap.incident,incidentAt,jobs,alternatives,fifo,selected:null};renderDecisionText();$('human').hidden=false;document.body.dataset.focus='true';decisionStart=performance.now();clearInterval(decisionTimer);decisionTimer=setInterval(()=>{const left=Math.max(0,20-Math.floor((performance.now()-decisionStart)/1000));$('decision-time').textContent=left;if(!left)choose('C',true);},200);renderComparison();}
function renderDecisionText(){
  if(!decision)return;
  const focused=document.activeElement?.closest('[data-choice]')?.dataset.choice;
  $('choices').innerHTML=Object.entries(decision.alternatives).map(([key,a],i)=>`<button data-choice="${key}">${T(key==='A'?'firstTrain':key==='B'?'secondTrain':'holdBoth',{id:shortId(decision.jobs[i===1?1:0].id)})}<small>${key==='C'?T('holdNote'):T('choiceResult',{delay:fmt(a.delay,1),conflicts:a.conflicts,delta:fmt(a.score-decision.fifo.score,1)})}</small></button>`).join('');
  if(focused)$('choices').querySelector(`[data-choice="${focused}"]`)?.focus({preventScroll:true});
  if(previewChoice){const a=decision.alternatives[previewChoice];$('choice-preview').textContent=T('choiceResult',{delay:fmt(a.delay,1),conflicts:a.conflicts,delta:fmt(a.score-decision.fifo.score,1)});}else $('choice-preview').textContent='';
  $('decision-log').textContent=decision.selected?T(decision.timed?'timeoutChoice':'selectedChoice',{choice:decision.selected})+' · '+clock(decision.chosenAt)+' · '+decisionCheckText():'';
}
function decisionCheckText(){if(!decision?.selected)return '';if(decision.validation==='pending')return T('decisionChecking');if(decision.validation==='error')return T('decisionCheckError');if(!decision.validation)return '';const result=decision.validation;if(result.accepted)return T('decisionAccepted');const codes=[...new Set(result.actions.flatMap(a=>a.issue_codes))];return T('decisionRejected')+(codes.length?' · '+codes.map(code=>T('issue_'+code)).join(', '):'');}
async function choose(key,timed=false){if(!decision||decision.selected)return;const game=decision;game.selected=key;game.timed=timed;game.chosenAt=snap.ts;game.validation='pending';clearInterval(decisionTimer);$('human').hidden=true;document.body.dataset.focus='false';renderDecisionText();renderComparison();navigate('comparison');try{const result=await api('/dispatch/decision',{elapsed_s:game.elapsed,incident:game.incident,incident_at_s:game.incidentAt,seed:game.seed,choice:key});if(result.snapshot_time!==game.ts||result.choice!==key)throw Error('snapshot mismatch');if(decision===game)game.validation=result;}catch{if(decision===game)game.validation='error';}if(decision===game)renderDecisionText();}
function renderComparison(){const body=$('comparison-body');const rows=[['humanStrategy',decision?.selected?decision.alternatives[decision.selected]:null],['FIFO',decision?.fifo],['CP-SAT',null],['CP-SAT + ML',null]];body.innerHTML=rows.map(([name,r])=>`<tr><td>${['humanStrategy'].includes(name)?T(name):name}</td>${r?`<td>${fmt(r.delay,1)}</td><td>${r.conflicts}</td><td>${fmt(r.ms,2)}</td><td>${fmt(r.energy,1)}</td>`:Array.from({length:4},()=>`<td>${T(name.startsWith('CP')?'notConnected':'noDecision')}</td>`).join('')}</tr>`).join('');}
async function loadEvidence(){evidenceLoaded=true;const e=$('evidence');try{const data=await api('/evidence.json');const table=(heads,rows)=>`<table><thead><tr>${heads.map(k=>`<th>${T(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const cal=data.growth_metrics.calibration;const calChart=`<svg viewBox="0 0 420 280"><path d="M45 20V235H395M45 235 395 20" fill="none" stroke="${colors.line}"/><polyline points="${cal.map(p=>`${45+p.predicted*350},${235-p.observed*215}`).join(' ')}" fill="none" stroke="${colors.green}" stroke-width="3"/>${[0,.25,.5,.75,1].map(n=>`<text x="${45+n*350}" y="260" text-anchor="middle">${n}</text><text x="30" y="${235-n*215}" text-anchor="end">${n}</text>`).join('')}</svg>`;
 const points=data.replay.points,range=Math.max(3,...points.map(p=>Math.abs(p.actual)),...points.map(p=>Math.abs(p.predicted))),line=key=>points.map((p,i)=>`${45+i/Math.max(1,points.length-1)*350},${135-p[key]/range*100}`).join(' ');const replay=`<svg viewBox="0 0 420 280"><path d="M45 20V235H395M45 135H395" fill="none" stroke="${colors.line}"/><polyline points="${line('actual')}" fill="none" stroke="${css('--freight')}" stroke-width="2"/><polyline points="${line('predicted')}" fill="none" stroke="${colors.green}" stroke-width="2"/>${[0,Math.floor(points.length/2),points.length-1].map(i=>`<text x="${45+i/Math.max(1,points.length-1)*350}" y="260" text-anchor="middle">${points[i].stop}</text>`).join('')}<text x="12" y="38">${fmt(range,0)}</text><text x="12" y="139">0</text><text x="8" y="238">−${fmt(range,0)}</text></svg>`;
 const shap=Object.entries(data.shap).sort((a,b)=>b[1]-a[1]).slice(0,8);let labels={};try{labels=await api('/locales/features-'+lang+'.json');}catch{}e.innerHTML=`<section class="full"><h3>${T('modelCard')}</h3><p>${T('modelCardText')}</p><span class="badge">${data.model_info.model_version}</span> <span class="badge">${data.model_info.rows.test.toLocaleString()} ${T('testRows')}</span><p>MAE ${fmt(data.model_info.regression.mae,3)} ${T('min')} · Brier ${fmt(data.growth_metrics.brier,4)} · ECE ${fmt(data.growth_metrics.ece,4)}</p></section><section class="full"><h3>${T('baselines')}</h3>${table(['bucket','model','zero','edgeMedian'],data.buckets.map(b=>[b.bucket==='all'?T('all'):b.bucket,...['model','zero','p50'].map(k=>fmt(b[k],3))]))}</section><section><h3>${T('calibration')}</h3><p>${T('calibrationNote')}</p>${calChart}</section><section><h3>${T('shap')}</h3><p>${T('shapNote')}</p>${shap.map(([key,n])=>`<div class="factor"><span>${esc(labels[key]||key)}</span><span>${fmt(n,3)}</span><div class="factor-track"><div class="factor-bar" style="transform:scaleX(${n/shap[0][1]})"></div></div></div>`).join('')}</section><section><h3>${T('replayPkp')} · ${data.replay.run_id}</h3><p>${T('replayNote')}</p>${replay}</section><section><h3>${T('whyNot')}</h3><p>${T('memorization')}</p><p>${T('formula')}</p><h3>${T('residualValidation')}</h3>${table(['bucket','formulaMaе','residualMae'],data.kz_group_folds.map(f=>[f.held_segments.join(' / '),fmt(f.formula_mae,2),fmt(f.residual_mae,2)]))}</section>`;}catch{e.textContent=T('requestError');}}
async function ask(question){if(chatBusy||!snap)return;chatBusy=true;$('send').disabled=true;const snapshot=currentState(),chosen=selected;const add=(text,cls='')=>{const p=document.createElement('p');p.className='message '+cls;p.textContent=text;$('messages').append(p);return p;};add(question,'user');const reply=add(T('checking'));$('chat-context').textContent=clock(snap.ts)+' · '+shortId(chosen)+' · '+T('chatBoundary');const a=advisories.find(a=>a.train_id===chosen);if(lang==='kk'){reply.textContent=T('chatLocalKk',{id:shortId(chosen),delay:fmt(train().delay_s/60,0),wait:fmt(a?.known_wait_min||0,0)});chatBusy=false;$('send').disabled=false;return;}
 const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),90000);try{const r=await fetch('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[...chatHistory.slice(-8),{role:'user',content:question+'\nВыбран '+chosen+'. KZ перенос не проверен. Не выдавай PKP число за надёжный прогноз. Известное ожидание: '+(a?.known_wait_min??'неизвестно')+' мин.'}],state:snapshot,session_id:'turkisib-redesign'}),signal:abort.signal});if(!r.ok)throw Error();const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',answer='',done=false;while(true){const chunk=await reader.read();buffer+=decoder.decode(chunk.value||new Uint8Array(),{stream:!chunk.done});let idx;while((idx=buffer.indexOf('\n\n'))>=0){const raw=buffer.slice(0,idx);buffer=buffer.slice(idx+2);const event=raw.split('\n').find(l=>l.startsWith('event:'))?.slice(6).trim(),line=raw.split('\n').find(l=>l.startsWith('data:'));if(!line)continue;const data=JSON.parse(line.slice(5));if(event==='token'){answer+=data.text;reply.textContent=answer;}if(event==='done')done=true;}if(chunk.done)break;}$('messages').scrollTop=$('messages').scrollHeight;if(!done||!answer)throw Error();if(a&&!a.reliable)reply.textContent=T('unreliable')+'. '+T('pkpTransfer')+'. '+T('knownWait')+': '+minute(a.known_wait_min||0)+'.\n'+answer;chatHistory.push({role:'user',content:question},{role:'assistant',content:reply.textContent});}catch{reply.textContent=T('chatError');}finally{clearTimeout(timeout);chatBusy=false;$('send').disabled=false;}}
function showTour(){const steps=[['tourMap','tourMapText','overview'],['tourIncident','tourIncidentText','scenarios'],['tourModel','tourModelText','lab'],['tourCompare','tourCompareText','comparison']];const [title,text,dest]=steps[tourStep%steps.length];$('tour').hidden=false;$('tour-title').textContent=T(title);$('tour-text').textContent=T(text);navigate(dest);}
async function changeIncident(value){incident=value;incidentAt=elapsed;ack=false;document.body.dataset.ack='false';$('incident').value=value;pause();experiment=null;try{applySnapshot(await api('/demo/snapshot?'+new URLSearchParams({elapsed,incident,incident_at:incidentAt})));calculate();resume();if(value!=='none'){buildDecision();$('focus-incident').click();$('choices').querySelector('button')?.focus({preventScroll:true});}else{clearInterval(decisionTimer);$('human').hidden=true;document.body.dataset.focus='false';}}catch(e){error(e.message);}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav)navigate(nav.dataset.page);const t=e.target.closest('[data-train]');if(t){select(t.dataset.train);openDrawer('train');}const s=e.target.closest('[data-station]');if(s){stationId=s.dataset.station;$('station-picker').value=stationId;openDrawer('station');}const c=e.target.closest('[data-choice]');if(c)choose(c.dataset.choice);const ev=e.target.closest('[data-incident]');if(ev)changeIncident(ev.dataset.incident);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();$('tour').hidden=true;}if(e.key==='ArrowRight'&&!$('tour').hidden&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){tourStep++;showTour();}if(['Enter',' '].includes(e.key)&&e.target.matches('svg [role=button]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
$('language').onchange=async e=>{lang=e.target.value;localStorage.setItem('turkisib-language',lang);await i18next.changeLanguage(lang);$('messages').replaceChildren();chatHistory=[];localize();};$('theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('motion-off').onchange=e=>{reduced=e.target.checked||matchMedia('(prefers-reduced-motion: reduce)').matches;document.documentElement.dataset.motion=reduced?'off':'on';};$('role').onchange=e=>{document.body.dataset.role=e.target.value;$('human').hidden=e.target.value==='manager'||!decision||!!decision.selected;};
$('forecast-retry').onclick=calculate;$('drawer-close').onclick=closeDrawer;$('train-picker').onchange=e=>select(e.target.value);$('station-picker').onchange=e=>{stationId=e.target.value;$('selected-title').textContent=stationName(stationId);renderStation();};$('play').onclick=()=>playing?pause():resume();$('tempo').onchange=e=>{tempo=Number(e.target.value);if(playing)connect();};$('reset').onclick=async()=>{pause();clearInterval(decisionTimer);elapsed=0;incident='none';incidentAt=0;$('incident').value='none';history=[];snap=null;experiment=null;decision=null;ack=false;$('human').hidden=true;document.body.dataset.focus='false';try{applySnapshot(await api('/demo/snapshot'));resume();renderComparison();}catch(e){error(e.message);}};$('incident').onchange=e=>changeIncident(e.target.value);
$('focus-incident').onclick=()=>{following=false;$('follow').setAttribute('aria-pressed','false');if(mapReady&&!schema)map.fitBounds([[70,51.7],[71.3,53]],{padding:65,duration:reduced?0:400});else{stationId='AKK';$('station-picker').value=stationId;renderStation();}};$('follow').onclick=()=>{following=!following;$('follow').setAttribute('aria-pressed',String(following));if(following)focusTrain();};$('fit').onclick=fit;$('schema-mode').onclick=()=>setSchema(true);$('map-mode').onclick=()=>mapReady?setSchema(false):error(T('noWebgl'));
['trains','occupancy','forecast','restrictions'].forEach(key=>$('layer-'+key).onchange=()=>{if(!mapReady)return;const layer={trains:'train-points',occupancy:'occupied',restrictions:'closed'}[key];if(layer)map.setLayoutProperty(layer,'visibility',$('layer-'+key).checked?'visible':'none');});
['delay','reserve'].forEach(id=>$(id).oninput=()=>{pause();experiment={id:selected,delay:Number($('delay').value),reserve:Number($('reserve').value)};renderInspector();calculate();});$('clear-experiment').onclick=()=>{experiment=null;renderInspector();calculate();};$('replay').oninput=()=>{pause();replaying=true;experiment=null;applySnapshot(history[Number($('replay').value)],false);$('replay-label').textContent=clock(snap.ts);calculate();};$('live').onclick=()=>{if(history.length)applySnapshot(history.at(-1),false);resume();};$('csv').onclick=()=>{const rows=['timestamp,train_id,block_id,km,speed_kmh,delay_s'];for(const s of history)for(const t of s.state.trains)rows.push([s.ts,t.train_id,t.position.block_id,t.position.km,t.speed,t.delay_s].join(','));const url=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='turkisib-kz-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('explain').onclick=()=>{closeDrawer();$('assistant').scrollIntoView({behavior:reduced?'auto':'smooth'});ask(T('explainQuestion'));};$('chat-form').onsubmit=e=>{e.preventDefault();const q=$('question').value.trim();if(q)ask(q);};$('show-abc').onclick=()=>{closeDrawer();if(!decision||decision.selected)buildDecision();$('human').hidden=false;};$('reject').onclick=()=>{$('chat-context').textContent=T('rejected');closeDrawer();};$('factors-toggle').onclick=()=>$('factors').hidden=!$('factors').hidden;$('acknowledge').onclick=()=>{ack=true;document.body.dataset.ack='true';document.body.dataset.focus='false';renderDashboard();};$('hint').onclick=()=>$('hint-text').hidden=false;
$('choices').onpointerover=e=>{const key=e.target.closest('[data-choice]')?.dataset.choice;if(!key||!decision)return;previewChoice=key;const a=decision.alternatives[key];$('choice-preview').textContent=T('choiceResult',{delay:fmt(a.delay,1),conflicts:a.conflicts,delta:fmt(a.score-decision.fifo.score,1)});};$('choices').onfocusin=$('choices').onpointerover;
$('axis').onchange=renderDiagram;$('horizon').onchange=()=>{zoomWindow=null;renderDiagram();};$('zoom-reset').onclick=()=>{zoomWindow=null;renderDiagram();};$('diagram').onpointerdown=e=>{if(e.target.closest('[data-train]'))return;dragStart=e.clientX;};$('diagram').onpointerup=e=>{if(dragStart===null)return;const rect=$('diagram').getBoundingClientRect(),{window:[lo,hi]}=diagramScale(),toTime=x=>lo+clamp(((x-rect.left)/rect.width*880-185)/670,0,1)*(hi-lo);if(Math.abs(e.clientX-dragStart)>20){zoomWindow=[toTime(Math.min(dragStart,e.clientX)),toTime(Math.max(dragStart,e.clientX))];renderDiagram();}dragStart=null;};$('diagram').onpointermove=e=>{const rect=$('diagram').getBoundingClientRect(),{window:[lo,hi]}=diagramScale(),m=lo+clamp(((e.clientX-rect.left)/rect.width*880-185)/670,0,1)*(hi-lo);$('crosshair').textContent=new Date(Date.parse(snap.ts)+m*60000).toLocaleTimeString(lang==='kk'?'kk-KZ':'ru-RU',{timeZone:'Asia/Almaty',hour12:false})+' · '+T('dragZoom');};
$('map-overlay').onpointermove=e=>{const id=e.target.closest('[data-train]')?.dataset.train;$('hover').hidden=!id;if(id){const t=snap.state.trains.find(t=>t.train_id===id);$('hover').textContent=shortId(id)+' · '+T(kind(t))+' · '+fmt(t.speed,0)+' '+T('kmh')+' · '+T('delay')+' '+minute(t.delay_s/60);}};$('map-overlay').onpointerleave=()=>$('hover').hidden=true;
$('tour-start').onclick=()=>{tourStep=0;showTour();};$('tour-next').onclick=()=>{tourStep++;showTour();};$('tour-close').onclick=()=>$('tour').hidden=true;
const chartResize=new ResizeObserver(()=>{for(const [id,units] of [['diagram',880],['station',400]]){const svg=$(id);if(svg.clientWidth)svg.style.setProperty('--label-size',`${Math.max(12,12*units/svg.clientWidth)}px`);}});chartResize.observe($('diagram'));chartResize.observe($('station'));
async function start(){try{const [ru,kk]=await Promise.all([fetch('/locales/ru.json').then(r=>r.json()),fetch('/locales/kk.json').then(r=>r.json())]);await i18next.init({lng:lang,fallbackLng:'ru',resources:{ru:{translation:ru},kk:{translation:kk}},interpolation:{escapeValue:false}});setTheme(localStorage.getItem('turkisib-theme')||'light');localize();const [g,c,s,h]=await Promise.all([api('/infra/geometry'),api('/kazakhstan.geojson'),api('/demo/snapshot'),api('/health')]);geo=g;country=c;selected=s.state.trains[0].train_id;$('train-picker').innerHTML=s.state.trains.map(t=>`<option value="${t.train_id}">${shortId(t.train_id)} · ${T(kind(t))} · ${s.display.find(d=>d.train_id===t.train_id).origin}</option>`).join('');$('station-picker').innerHTML=geo.stations.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('station-picker').value=stationId;$('chat-provider').textContent=T(h.llm_configured?'llmReady':'llmFallback');applySnapshot(s);calculate();initializeMap();$('play').disabled=false;connect();requestAnimationFrame(frame);renderComparison();if(location.hash==='#lab')navigate('lab');}catch(e){error(e.message||'Service unavailable');}}
let analysisResult=null,analysisBusy=false,analysisInitialized=false;
function planStatus(status){const key={OPTIMAL:'planOptimal',FEASIBLE:'planFeasible',INFEASIBLE:'planInfeasible',TIMEOUT:'planTimeout',NOT_REQUESTED:'planNotRequested',UNAVAILABLE:'analysisUnavailable',UNSUPPORTED_SCENARIO:'analysisUnsupported'}[status];return key?T(key):status||'—';}
function renderAnalysis(){
  if(!analysisResult)return;
  const r=analysisResult,c=r.cp_sat;
  $('platform-results').hidden=false;
  $('analysis-snapshot').textContent=clock(r.snapshot_time)+' · '+r.snapshot_id;
  $('analysis-fifo').textContent=T('analysisCount',{count:r.fifo.ordered_train_ids.length});
  $('analysis-cpsat').textContent=planStatus(c.status)+(c.reservation_count?' · '+T('reservationCount',{count:c.reservation_count}):'');
  $('analysis-validator').textContent=c.valid===true?T('analysisValid'):c.valid===false?T('analysisInvalid'):T('analysisNotChecked');
  $('analysis-order').textContent=r.fifo.ordered_train_ids.join(' → ');
  const rows=(c.reservations||[]).filter(v=>v.train_id===selected&&v.resource_type==='block').slice(0,12);
  $('analysis-reservations').innerHTML=rows.length?rows.map(v=>`<div class="reservation-row"><span>${esc(v.resource_id)}</span><span class="mono">${clock(v.start)}–${clock(v.end)}</span></div>`).join(''):T('noReservations');
  $('analysis-scope').textContent=T('pairLabel')+': '+r.pair_train_ids.join(' / ')+' · '+T('reservationCount',{count:c.reservation_count||0})+' · '+T('plannerSeed')+': '+r.seed+' · '+T('fullCpSatLabel')+': '+planStatus(r.full_cp_sat?.status);
  $('analysis-limitations').textContent=(r.snapshot_overlaps?.length?T('snapshotOverlap',{count:r.snapshot_overlaps.length})+' ':'')+T('analysisLimitations');
  $('platform-status').textContent=Math.abs((snap?.elapsed_s??r.elapsed_s)-r.elapsed_s)>1||incident!==r.incident||incidentAt!==r.incident_at_s?T('analysisStale'):T('analysisReady');
}
async function runAnalysis(){
  if(!snap||analysisBusy)return;
  const captured={elapsed_s:snap.elapsed_s,incident:snap.incident,incident_at_s:incidentAt,seed:Number($('seed').value)||42};
  const restoreFocus=document.activeElement===$('run-analysis');
  analysisBusy=true;$('run-analysis').disabled=true;$('platform-status').textContent=T('analysisLoading');
  try{analysisResult=await api('/dispatch/analysis',captured);renderAnalysis();}
  catch{analysisResult=null;$('platform-results').hidden=true;$('platform-status').textContent=T('analysisError');}
  finally{analysisBusy=false;$('run-analysis').disabled=false;if(restoreFocus)$('run-analysis').focus({preventScroll:true});}
}
$('run-analysis').onclick=runAnalysis;
i18next.on('languageChanged',()=>{if(analysisResult)renderAnalysis();});
start();
