import {tr} from './locales.js';
import {createScene} from './scene.js';
import {acceptFrame,diagramData,speedAdvice,formatClock as clock} from './realtime-data.mjs';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=value=>Number.isFinite(value)?value.toFixed(1):'—';
const state={snapshot:null,history:[],geo:null,selected:null,station:'AST',section:'north',view:'map',paused:false,replay:false,tempo:'1',incident:'none',incidentAt:0,analysis:null,context:null};
let cleanup=()=>{};
export function disposeRealtime(){cleanup();cleanup=()=>{};}

export async function mountRealtime({lang,dark,onLanguage,onTheme}){
  const T=(key,params={})=>tr(key,lang).replace(/\{(\w+)\}/g,(_,name)=>params[name]??'');
  const $=id=>document.getElementById(id),controller=new AbortController();
  let active=true,stream,retryTimer,retries=0,map,scene,sceneKey='',markers=new Map(),stationMarkers=new Map(),railLayers=new Map(),requestId=0,busy=false,wantPlan=false,lastAnalysis=0,connected=false;
  document.getElementById('app').innerHTML=`<div class="desk"><header class="desk-header"><a href="#dispatch" class="brand"><img src="/brand.svg" alt=""><strong>Jibek Joly</strong></a><span id="rt-connection" role="status">${T('loading')}</span><strong id="rt-clock" class="mono">—</strong><div class="lang"><button id="rt-ru" aria-pressed="${lang===0}">RU</button><button id="rt-kk" aria-pressed="${lang===1}">KZ</button></div><button id="rt-theme">${T(dark?'rtLight':'rtDark')}</button></header>
  <main class="desk-main"><div class="desk-heading"><div><h1>${T('rtTitle')}</h1><p>${T('rtSource')} ${lang?T('translation'):''}</p></div><div class="desk-controls"><label>${T('rtIncident')}<select id="rt-incident"><option value="none">${T('noIncident')}</option><option value="closure">${T('closure')}</option><option value="restriction">${T('rtRestriction')}</option><option value="chaos">${T('rtCascade')}</option></select></label><label>${T('rtTempo')}<select id="rt-tempo"><option value="1">1×</option><option value="10">10×</option></select></label><button id="rt-play">${T(state.paused?'play':'pause')}</button><button id="rt-reset">${T('reset')}</button></div></div>
  <div id="rt-error" class="info bad" role="alert" hidden><span>${T('networkError')}</span><button id="rt-retry">${T('retry')}</button></div>
  <section class="operations-strip" aria-label="${T('rtSummary')}"><div><span>${T('rtQuality')}</span><strong id="rt-score" class="mono">—</strong><span id="rt-category"></span></div><div><span>${T('rtMeanDelay')}</span><strong id="rt-delay" class="mono">—</strong></div><div><span>${T('rtConflict')}</span><strong id="rt-conflicts" class="mono">—</strong></div><div><span>${T('rtTrainCount')}</span><strong id="rt-count" class="mono">—</strong></div><details><summary>${T('rtFormula')}</summary><p>${T('rtFormulaNote')}</p><div id="rt-factors"></div></details></section>
  <div class="desk-layout"><aside class="station-rail"><h2>${T('rtStations')}</h2><div id="rt-stations"></div><p>${T('rtStationNote')}</p></aside><div class="desk-instruments"><div class="desk-upper"><section class="panel live-map-panel"><div class="panel-head"><div class="view-tabs"><button id="rt-map-view" aria-pressed="true">${T('rtMap')}</button><button id="rt-3d-view" aria-pressed="false">${T('rtStation3d')}</button></div><label>${T('rtSection')}<select id="rt-section"><option value="north">Көкшетау — Астана</option><option value="south">Астана — Алматы</option><option value="all">${T('rtAll')}</option></select></label></div><div id="rt-map"></div><div id="rt-scene" hidden></div><div class="station-toolbar" id="rt-scene-controls" hidden><strong id="rt-station-name"></strong><button id="rt-top">${T('rtTop')}</button><button id="rt-camera">${T('rtCamera')}</button></div><p id="rt-map-note" class="panel-copy">${T('rtMapNote')}</p><div id="rt-arrivals" hidden></div></section>
  <aside class="live-advice"><section class="panel"><div class="panel-head"><h2>${T('rtDriving')}</h2></div><div class="panel-body"><label class="train-field">${T('selected')}<select id="rt-train"></select></label><div id="rt-train-facts" class="train-facts"></div><div class="speed-advice"><span>${T('rtRecommended')}</span><strong id="rt-speed" class="mono">—</strong><p id="rt-speed-reason" role="status"></p></div><svg id="rt-speed-plot" viewBox="0 0 420 130" role="img" aria-label="${T('rtDriving')}"></svg><p class="caption">${T('rtSpeedNote')}</p></div></section>
  <section class="panel"><div class="panel-head"><h2>${T('rtPlan')}</h2><button id="rt-replan">${T('rtRecalculate')}</button></div><div class="panel-body"><p class="caption">${T('rtPlanScope')}</p><div id="rt-plan" aria-live="polite">${T('loading')}</div></div></section></aside></div>
  <section class="panel diagram-panel"><div class="panel-head"><h2>${T('diagram')}</h2><span id="rt-diagram-count" class="meta"></span></div><div class="diagram-legend"><span class="legend-plan">${T('rtScheduled')}</span><span class="legend-observed">${T('rtObserved')}</span><span class="legend-future">${T('rtContinuation')}</span></div><div class="diagram-scroll" tabindex="0"><svg id="rt-diagram" viewBox="0 0 960 460" role="img" aria-label="${T('diagram')}"></svg></div><p class="panel-copy">${T('rtDiagramNote')}</p><div class="history-controls"><label for="rt-history">${T('history')}</label><input id="rt-history" type="range" min="0" max="0" value="0"><button id="rt-live">${T('toLive')}</button><button id="rt-csv">CSV</button><span id="rt-history-label" role="status"></span></div></section>
  <details class="panel train-register"><summary>${T('rtRegister')}</summary><div class="table-scroll"><table><thead><tr><th>${T('train')}</th><th>${T('rtNextStation')}</th><th>${T('speed')}</th><th>${T('delay')}</th></tr></thead><tbody id="rt-register"></tbody></table></div></details></div></div><footer class="desk-footer">${T('rtFooter')}</footer></main></div>`;
  document.querySelector('.desk-instruments').prepend(document.querySelector('.diagram-panel'));
  document.querySelector('.diagram-panel .panel-head').append($('rt-section').closest('label'));
  const controls=['rt-play','rt-reset','rt-incident','rt-tempo','rt-replan','rt-section','rt-train','rt-map-view','rt-3d-view','rt-history','rt-live','rt-csv'];
  const enable=value=>controls.forEach(id=>$(id).disabled=!value);
  enable(false);
  $('rt-ru').onclick=()=>onLanguage(0);$('rt-kk').onclick=()=>onLanguage(1);$('rt-theme').onclick=onTheme;
  const request=async(url,body)=>{const r=await fetch(url,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(!r.ok)throw Error('HTTP '+r.status);return r.json();};
  const status=()=>{$('rt-connection').textContent=T(state.replay?'rtReplay':state.paused?'paused':connected?'running':'frozen');$('rt-play').textContent=T(state.paused?'play':'pause');};
  cleanup=()=>{active=false;requestId++;clearTimeout(retryTimer);controller.abort();stream?.close();map?.remove();scene?.dispose();};
  const name=id=>state.geo.stations.find(s=>s.id===id)?.name||id;
  const error=()=>{if(active){$('rt-error').hidden=false;connected=false;status();}};
  const context=()=>({elapsed_s:state.snapshot.elapsed_s,incident:state.context.incident,incident_at_s:state.context.incidentAt,seed:42});
  function fitMap(){const g=state.geo.stations,ast=g.find(s=>s.id==='AST').km;const rows=g.filter(s=>state.section==='all'||(state.section==='north'?s.km<=ast:s.km>=ast));map.fitBounds(rows.map(s=>[s.coordinates[1],s.coordinates[0]]),{padding:[35,40],maxZoom:9});}
  function color(t){return t.train_id===state.selected?(dark?'#88baff':'#1d5fa8'):t.type==='груз'?'#94684a':'#8464b6';}
  function drawMap(){const snap=state.snapshot;
    for(const t of snap.state.trains){const block=state.geo.features.find(f=>f.properties.id===t.position.block_id);if(!block)continue;const c=block.geometry.coordinates,a=c[0],b=c.at(-1),f=Math.min(1,Math.max(0,t.position.km/block.properties.length_km));const p=[a[1]+(b[1]-a[1])*f,a[0]+(b[0]-a[0])*f];let marker=markers.get(t.train_id);if(!marker){marker=L.circleMarker(p,{radius:4,weight:2,fillOpacity:.95}).addTo(map).bindTooltip(t.train_id).on('click',()=>select(t.train_id));markers.set(t.train_id,marker);}marker.setLatLng(p).setStyle({color:color(t),fillColor:color(t),radius:t.train_id===state.selected?8:4});}
    for(const b of snap.state.infra.blocks){const layer=railLayers.get(b.id);if(layer)layer.setStyle({color:b.closed?'#c0392b':'#8a93a1',weight:b.closed?5:2,dashArray:b.closed?'6 3':null});}
    for(const [id,marker]of stationMarkers)marker.setStyle({radius:id===state.station?7:5,color:id===state.station?'#1d5fa8':'#394859'});
  }
  function drawDiagram(){const d=diagramData(state.geo,state.snapshot,state.history.map(h=>h.data),state.selected,state.section);const h=d.height,plot=p=>`${d.x(p.ms)},${d.y(p.km)}`;let svg=`<defs><clipPath id="rt-plot"><rect x="170" y="24" width="760" height="${h-45}"/></clipPath></defs>`;
    for(const s of d.stations)svg+=`<path d="M170 ${s.y}H930" stroke="var(--line)"/><text x="155" y="${s.y+4}" text-anchor="end">${esc(s.name)}</text>`;
    for(let i=0;i<=9;i++){const at=d.start+i*5*60000,x=d.x(at);svg+=`<path d="M${x} 24V${h-12}" stroke="var(--line)"/><text x="${x}" y="${h+14}" text-anchor="middle">${clock(at).slice(0,5)}</text>`;}
    svg+='<g clip-path="url(#rt-plot)">';
    for(const row of [...d.trains].sort((a,b)=>Number(a.selected)-Number(b.selected))){const col=row.selected?'var(--accent)':row.freight?'#94684a':'#8464b6';svg+=`<g data-train="${esc(row.id)}" role="button" tabindex="0" aria-label="${esc(row.id)}" opacity="${row.selected?1:.33}"><polyline class="timetable-path" points="${row.planned.map(plot).join(' ')}" fill="none" stroke="${col}" stroke-width="1.3"/><polyline class="observed-path" points="${row.observed.map(plot).join(' ')}" fill="none" stroke="${col}" stroke-width="${row.selected?4:2}"/><polyline class="continuation-path" points="${row.forecast.map(plot).join(' ')}" fill="none" stroke="${col}" stroke-width="${row.selected?2.5:1.5}" stroke-dasharray="7 5"/><polyline points="${row.forecast.map(plot).join(' ')}" fill="none" stroke="transparent" stroke-width="14"/><circle cx="${d.x(d.now)}" cy="${d.y(row.current.km)}" r="${row.selected?6:3}" fill="${col}"/><title>${esc(row.id)}</title></g>`;}
    svg+=`</g><path d="M${d.x(d.now)} 24V${h-12}" stroke="var(--accent)" stroke-width="1.5"/><text x="${d.x(d.now)+9}" y="20">${T('rtNow')} · ${clock(state.snapshot.ts).slice(0,5)}</text>`;
    const focused=document.activeElement?.closest('#rt-diagram [data-train]')?.dataset.train;
    $('rt-diagram').setAttribute('viewBox',`0 0 960 ${h+40}`);$('rt-diagram').innerHTML=svg;
    if(focused)$('rt-diagram').querySelector(`[data-train="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});
    $('rt-diagram-count').textContent=T('rtVisibleTrains',{count:d.trains.length});
  }
  function drawAdvice(){const snap=state.snapshot,t=snap.state.trains.find(t=>t.train_id===state.selected),d=snap.display.find(t=>t.train_id===state.selected),advice=speedAdvice(snap,state.geo,state.selected);if(!t||!d)return;
    $('rt-train').value=state.selected;$('rt-train-facts').innerHTML=`<span>${T('rtNextStation')}<strong>${esc(name(d.next_station))}</strong></span><span>${T('speed')}<strong>${num(t.speed)} ${T('kmh')}</strong></span><span>${T('distance')}<strong>${num(d.distance_to_station_km)} ${T('rtKm')}</strong></span><span>${T('rtDue')}<strong class="mono">${clock(d.scheduled_arrival).slice(0,5)}</strong></span>`;
    $('rt-speed').textContent=num(advice.recommendedKmh);$('rt-speed-reason').textContent=T('rtSpeed_'+advice.status);
    const cap=advice.capKmh||1,y=v=>100-v/cap*75;
    $('rt-speed-plot').innerHTML=`<path d="M35 15V100H400" stroke="var(--muted)" fill="none"/><text x="35" y="123">0</text><text x="400" y="123" text-anchor="end">${num(advice.distanceKm)} ${T('rtKm')}</text>${advice.capKmh?`<path d="M35 25H400" stroke="var(--amber)" stroke-dasharray="4 4"/><text x="35" y="17">${T('rtCap')}: ${num(advice.capKmh)} ${T('kmh')}</text>`:''}${advice.recommendedKmh!==null?`<path d="M35 ${y(advice.recommendedKmh)}H400" stroke="var(--accent)" stroke-width="3"/><text x="45" y="${Math.max(42,y(advice.recommendedKmh)-8)}">${num(advice.recommendedKmh)} ${T('kmh')}</text>`:''}`;
  }
  function drawStation(){const s=state.geo.stations.find(s=>s.id===state.station);if(!s)return;$('rt-station-name').textContent=s.name;
    const snap=state.snapshot,near=snap.display.filter(d=>Math.abs(d.corridor_km-s.km)<20||d.next_station===s.id).sort((a,b)=>Math.abs(a.corridor_km-s.km)-Math.abs(b.corridor_km-s.km)).slice(0,Math.max(s.tracks,4));
    if(state.view==='3d'){const key=s.id+'|'+Boolean(snap.stations.find(r=>r.id===s.id)?.problem)+'|'+state.selected+'|'+near.map(d=>d.train_id).join('|');if(key!==sceneKey){scene?.dispose();scene=createScene($('rt-scene'),{tracks:s.tracks,name:s.name,lang,dark,trains:near.map((d,i)=>({id:d.train_id,track:i%s.tracks+1,color:color(snap.state.trains.find(t=>t.train_id===d.train_id))})),onSelect:t=>select(t.id),blocked:snap.stations.find(r=>r.id===s.id)?.problem});sceneKey=key;}scene.setPositions?.(near.map(d=>({id:d.train_id,progress:Math.min(1,Math.max(0,.5+(d.corridor_km-s.km)*d.direction/40))})));}
    const arrivals=snap.display.filter(d=>d.next_station===s.id&&d.scheduled_arrival).sort((a,b)=>Date.parse(a.scheduled_arrival)-Date.parse(b.scheduled_arrival));
    $('rt-arrivals').innerHTML=`<h3>${T('rtArrivals')}</h3>${arrivals.length?arrivals.slice(0,8).map(d=>`<button data-train="${esc(d.train_id)}" class="arrival-line"><span class="mono">${esc(d.train_id)}</span><span>${clock(d.scheduled_arrival).slice(0,5)}</span><span>${d.held?T('rtHeld'):d.eta_s===null?'—':clock(new Date(Date.parse(snap.ts)+d.eta_s*1000).toISOString()).slice(0,5)}</span></button>`).join(''):`<p>${T('rtNoArrivals')}</p>`}<p class="caption">${T('rtArrivalNote')}</p>`;
    $('rt-map-note').textContent=T(state.view==='3d'?'rtSceneNote':'rtMapNote');
  }
  function view(mode,focus=false){state.view=mode; $('rt-map').hidden=mode!=='map';$('rt-scene').hidden=mode!=='3d';$('rt-scene-controls').hidden=mode!=='3d';$('rt-arrivals').hidden=mode!=='3d';$('rt-map-view').setAttribute('aria-pressed',mode==='map');$('rt-3d-view').setAttribute('aria-pressed',mode==='3d');if(mode==='map'){scene?.dispose();scene=null;sceneKey='';requestAnimationFrame(()=>map.invalidateSize());}else {drawStation();if(focus)document.querySelector('.live-map-panel').scrollIntoView({block:'start'});}}
  function select(id){if(!state.snapshot.state.trains.some(t=>t.train_id===id))return;state.selected=id;const d=state.snapshot.display.find(d=>d.train_id===id),endpoints=[d.origin,d.destination];state.section=endpoints.includes('KOK')&&endpoints.includes('ALM')?'all':endpoints.includes('KOK')?'north':'south';$('rt-section').value=state.section;fitMap();drawDiagram();drawAdvice();drawMap();drawRegister();drawStation();}
  function drawRegister(){const snap=state.snapshot;if(!$('rt-register').children.length)$('rt-register').innerHTML=snap.state.trains.map(t=>`<tr data-id="${esc(t.train_id)}"><td><button data-train="${esc(t.train_id)}" class="train-select">${esc(t.train_id)}</button></td><td></td><td></td><td></td></tr>`).join('');for(const row of $('rt-register').children){const t=snap.state.trains.find(t=>t.train_id===row.dataset.id),d=snap.display.find(d=>d.train_id===row.dataset.id);if(!t||!d)continue;row.classList.toggle('selected-row',t.train_id===state.selected);row.cells[1].textContent=name(d.next_station);row.cells[2].textContent=num(t.speed);row.cells[3].textContent=num(t.delay_s/60);}}
  function draw(){const snap=state.snapshot;if(!snap)return;$('rt-clock').textContent=clock(snap.ts)+' · UTC+5';$('rt-score').textContent=snap.quality.score+' /100';$('rt-category').textContent=T('rtQuality_'+snap.quality.category);$('rt-delay').textContent=num(snap.state.trains.reduce((n,t)=>n+t.delay_s,0)/snap.state.trains.length/60)+' '+T('ref008');$('rt-count').textContent=snap.state.trains.length+' SIM';
    const occupancy=new Map();for(const t of snap.state.trains){const id=t.position.block_id;occupancy.set(id,(occupancy.get(id)||0)+1);}const count=[...occupancy.values()].filter(v=>v>1).length;$('rt-conflicts').textContent=count;$('rt-conflicts').className=count?'bad mono':'mono';
    $('rt-factors').innerHTML=snap.quality.factors.map(f=>`<div><span>${T('rtFactor_'+f.key)}</span><strong class="mono">−${num(f.points)}</strong></div>`).join('');
    for(const button of $('rt-stations').children){const station=snap.stations.find(s=>s.id===button.dataset.station);button.classList.toggle('active',button.dataset.station===state.station);button.querySelector('small').textContent=station?`${station.occupied} / ${station.capacity}`:'—';}
    drawMap();drawDiagram();drawAdvice();drawRegister();drawStation();$('rt-history-label').textContent=T(state.replay?'rtReplay':'rtHistoryCount',{count:state.history.length});status();
  }
  function apply(data,record=false,ctx={incident:state.incident,incidentAt:state.incidentAt}){if(!acceptFrame(null,data))throw Error('Invalid snapshot');state.snapshot=data;state.context=ctx;state.selected ||= data.state.trains[0].train_id;if(record){state.history.push({data,context:ctx});while(state.history.length>900||(state.history.length>1&&Date.parse(data.ts)-Date.parse(state.history[0].data.ts)>900000))state.history.shift();$('rt-history').max=state.history.length-1;$('rt-history').value=state.history.length-1;}draw();}
  function connect(){clearTimeout(retryTimer);stream?.close();if(!active||state.paused||state.replay||!state.snapshot)return;const source=new EventSource('/demo/stream?'+new URLSearchParams({elapsed:state.snapshot.elapsed_s,speed:state.tempo,incident:state.incident,incident_at:state.incidentAt}));stream=source;
    source.addEventListener('state',event=>{if(!active||stream!==source||state.paused||state.replay)return;try{const data=JSON.parse(event.data);if(!acceptFrame(state.snapshot,data))return;connected=true;retries=0;apply(data,true);$('rt-error').hidden=true;if(!busy&&Date.now()-lastAnalysis>30000&&!state.replay)replan();}catch{error();}});
    source.onerror=()=>{source.close();if(active&&stream===source){error();retryTimer=setTimeout(connect,Math.min(10000,1000*2**retries++));}};
  }
  async function refresh(reset=false){const ticket=++requestId;stream?.close();stream=null;clearTimeout(retryTimer);connected=false;state.analysis=null;$('rt-plan').textContent=T('loading');$('rt-replan').disabled=true;try{const data=await request('/demo/snapshot?'+new URLSearchParams({elapsed:reset?0:state.snapshot?.elapsed_s||0,incident:state.incident,incident_at:state.incidentAt}));if(!active||ticket!==requestId)return;apply(data,true);$('rt-error').hidden=true;connected=true;connect();replan();}catch(e){if(e.name!=='AbortError')error();}finally{if(active)$('rt-replan').disabled=busy;}}
  function planView(result){const good=result.cp_sat.valid===true,reservations=result.cp_sat.reservations||[];$('rt-plan').innerHTML=`<div class="plan-state ${good?'good':'warn'}"><strong>${T(good?'rtPlanChecked':result.cp_sat.status==='UNSUPPORTED_SCENARIO'?'rtPlanUnsupported':'rtPlanUnavailable')}</strong><span>${T('captured')}: ${clock(result.snapshot_time)}</span></div><p>${T('rtPlanTrains')}: <span class="mono">${esc(result.pair_train_ids.join(' / '))}</span></p>${good?`<details><summary>${T('rtBlockWindows',{count:reservations.length})}</summary><div class="plan-windows">${reservations.map(r=>`<div><strong class="mono">${esc(r.train_id)}</strong><span>${esc(r.resource_id)} · ${clock(r.start).slice(0,5)} — ${clock(r.end).slice(0,5)}</span></div>`).join('')}</div></details>`:''}<p class="caption">${T('rtFullPlan')}: ${result.full_cp_sat.status==='OPTIMAL'||result.full_cp_sat.status==='FEASIBLE'?T('rtPlanBuilt'):T('rtFullUnavailable')}</p>`;}
  async function replan(){if(!active||!state.snapshot)return;if(busy){wantPlan=true;return;}busy=true;const ticket=requestId,body=context();lastAnalysis=Date.now();$('rt-replan').disabled=true;$('rt-plan').textContent=T('calculating');try{const result=await request('/dispatch/analysis',body);if(!active||ticket!==requestId)return;state.analysis=result;planView(result);}catch(e){if(active&&ticket===requestId&&e.name!=='AbortError')$('rt-plan').textContent=T('rtPlanError');}finally{busy=false;if(active){$('rt-replan').disabled=false;if(wantPlan){wantPlan=false;replan();}}}}
  document.getElementById('app').addEventListener('click',event=>{const target=event.target.closest('[data-train],[data-station]');if(!target||!state.snapshot)return;if(target.dataset.train)select(target.dataset.train);if(target.dataset.station){state.station=target.dataset.station;location.hash='station/'+state.station;view('3d',true);draw();}},{signal:controller.signal});
  $('rt-diagram').addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.dataset.train){event.preventDefault();select(event.target.dataset.train);}},{signal:controller.signal});
  $('rt-map-view').onclick=()=>{location.hash='dispatch';view('map');};$('rt-3d-view').onclick=()=>{location.hash='station/'+state.station;view('3d',true);};$('rt-top').onclick=()=>scene?.top();$('rt-camera').onclick=()=>scene?.reset();$('rt-train').onchange=e=>select(e.target.value);
  $('rt-section').onchange=()=>{state.section=$('rt-section').value;fitMap();drawDiagram();};
  $('rt-tempo').value=state.tempo;$('rt-tempo').onchange=()=>{state.tempo=$('rt-tempo').value;connect();};
  $('rt-play').onclick=()=>{if(state.replay){const latest=state.history.at(-1);if(latest)apply(latest.data,false,latest.context);state.replay=false;}state.paused=!state.paused;status();if(state.paused)stream?.close();else connect();};
  $('rt-reset').onclick=()=>{state.history=[];state.paused=false;state.replay=false;state.incident='none';state.incidentAt=0;$('rt-incident').value='none';refresh(true);};
  $('rt-incident').value=state.incident;$('rt-incident').onchange=()=>{restoreLatest();state.incident=$('rt-incident').value;state.incidentAt=state.snapshot.elapsed_s;refresh();};
  $('rt-history').oninput=()=>{const row=state.history[Number($('rt-history').value)];if(!row)return;requestId++;stream?.close();state.paused=true;state.replay=true;apply(row.data,false,row.context);state.analysis=null;$('rt-plan').textContent=T('rtReplayPlan');};
  $('rt-live').onclick=()=>{const row=state.history.at(-1);if(row)apply(row.data,false,row.context);state.replay=false;state.paused=false;status();connect();if(state.analysis)planView(state.analysis);else replan();};
  $('rt-csv').onclick=()=>{const rows=['timestamp,train_id,block_id,speed_kmh,delay_min,quality_index'];for(const {data:s} of state.history)for(const t of s.state.trains)rows.push([s.ts,t.train_id,t.position.block_id,t.speed,t.delay_s/60,s.quality.score].join(','));const url=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\r\n')],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='jibek-joly-realtime.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  function restoreLatest(){if(state.replay){const row=state.history.at(-1);if(row)apply(row.data,false,row.context);state.replay=false;}}
  $('rt-replan').onclick=replan;$('rt-retry').onclick=()=>{restoreLatest();if(map)refresh();else initialize();};
  function applyRoute(){if(!state.geo||!state.snapshot||!map)return;const route=location.hash.slice(1).split('/'),alias={astana1:'AST',nurly:'AST',kokshetau:'KOK',almaty2:'ALM'};const id=alias[route[1]]||route[1];if(route[0]==='station'&&state.geo.stations.some(s=>s.id===id)){state.station=id;view('3d');}else view('map');draw();}
  window.addEventListener('hashchange',applyRoute,{signal:controller.signal});
  async function initialize(){enable(false);try{
    if(!state.geo)state.geo=await request('/infra/geometry');if(!active)return;
    if(!state.snapshot){const data=await request('/demo/snapshot');if(!active)return;state.snapshot=data;state.context={incident:state.incident,incidentAt:state.incidentAt};}
    const route=location.hash.slice(1).split('/'),alias={astana1:'AST',nurly:'AST',kokshetau:'KOK',almaty2:'ALM'};if(route[0]==='station'){const id=alias[route[1]]||route[1];if(state.geo.stations.some(s=>s.id===id)){state.station=id;state.view='3d';}}
    $('rt-stations').innerHTML=state.geo.stations.map(s=>`<button data-station="${s.id}"><span>${esc(s.name)}</span><small>—</small></button>`).join('');
    $('rt-train').innerHTML=state.snapshot.state.trains.map(t=>`<option value="${esc(t.train_id)}">${esc(t.train_id)}</option>`).join('');$('rt-section').value=state.section;
    map?.remove();markers.clear();stationMarkers.clear();railLayers.clear();map=L.map('rt-map',{scrollWheelZoom:false}).setView([52,71],7);L.geoJSON(state.geo,{style:{color:'#8a93a1',weight:2},onEachFeature:(f,layer)=>railLayers.set(f.properties.id,layer)}).addTo(map);
    for(const s of state.geo.stations){const marker=L.circleMarker([s.coordinates[1],s.coordinates[0]],{radius:5,fillColor:dark?'#243140':'#fff',fillOpacity:1,color:'#394859',weight:2}).addTo(map).bindTooltip(s.name,{direction:'right'}).on('click',()=>{state.station=s.id;location.hash='station/'+s.id;view('3d',true);draw();});stationMarkers.set(s.id,marker);}
    request('/kazakhstan.geojson').then(g=>{if(active)L.geoJSON(g,{style:{color:'#8a9ca6',weight:1,fillColor:dark?'#243140':'#e8dcc2',fillOpacity:.3}}).addTo(map).bringToBack();}).catch(()=>{});
    fitMap();connected=true;if(!state.history.length)apply(state.snapshot,true);else apply(state.snapshot,false,state.context);$('rt-history').max=state.history.length-1;$('rt-history').value=state.history.length-1;applyRoute();enable(true);$('rt-error').hidden=true;connect();if(state.analysis)planView(state.analysis);else replan();
  }catch(e){map?.remove();map=null;scene?.dispose();scene=null;sceneKey='';if(e.name!=='AbortError'){console.error('Realtime initialization failed',e);error();}}}
  initialize();
}
